/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List all sessions with optional filtering.
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a new session.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Get session details with all related data.
         */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete a session and all related data.
         */
        delete: operations["delete_session_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Send a chat message and stream the response via SSE.
         *
         *     Messages are stored via LangGraph checkpointer, not in a separate table.
         */
        post: operations["chat_sessions__session_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Tasks
         * @description Execute all pending tasks for a session and stream progress via SSE.
         *
         *     This endpoint:
         *     1. Fetches all pending tasks for the session
         *     2. Executes each task sequentially using the execution agent
         *     3. Streams real-time events for each task's progress
         *     4. Updates task status in the database
         *
         *     Events emitted:
         *     - task_selected: When a task is picked for execution
         *     - tool_call: When the agent calls a tool
         *     - tool_result: When a tool returns a result
         *     - task_completed: When a task finishes (done/failed)
         *     - reflection: Agent's reflection on task completion
         *     - error: When an error occurs
         *     - done: When all tasks are processed
         */
        post: operations["execute_tasks_sessions__session_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize Session
         * @description Generate execution summary and stream as chat message.
         *
         *     This endpoint is called by the frontend after execution completes.
         *     It generates a conversational summary using the planning agent and
         *     saves only the AI response to the checkpoint (no fake user message).
         *
         *     Events emitted:
         *     - content: Streamed summary text
         *     - done: Summary complete
         *     - error: When an error occurs
         */
        post: operations["summarize_session_sessions__session_id__summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/execution-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Execution Logs
         * @description Get execution logs for a session.
         *
         *     Returns all execution events that were generated during task execution.
         *     Used to restore the execution log view when reloading a session.
         */
        get: operations["get_execution_logs_sessions__session_id__execution_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description List all artifacts for a session.
         */
        get: operations["list_artifacts_sessions__session_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Get a single artifact with full content.
         */
        get: operations["get_artifact_sessions__session_id__artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Artifact
         * @description Delete an artifact.
         */
        delete: operations["delete_artifact_sessions__session_id__artifacts__artifact_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/artifacts/{artifact_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Artifact
         * @description Download an artifact as a file.
         */
        get: operations["download_artifact_sessions__session_id__artifacts__artifact_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Artifact
         * @description Artifact model with all fields.
         */
        Artifact: {
            /** Name */
            name: string;
            type: components["schemas"]["ArtifactType"];
            /** Content */
            content: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /** Taskid */
            taskId?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * ArtifactSummary
         * @description Artifact summary without content for listing.
         */
        ArtifactSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /** Taskid */
            taskId?: string | null;
            /** Name */
            name: string;
            type: components["schemas"]["ArtifactType"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * ArtifactType
         * @description Artifact type enum.
         * @enum {string}
         */
        ArtifactType: "document" | "note" | "summary" | "plan" | "other";
        /**
         * ChatRequest
         * @description Chat message request body.
         */
        ChatRequest: {
            /** Message */
            message: string;
        };
        /**
         * CheckpointMessage
         * @description Message from LangGraph checkpoint state.
         *
         *     Simpler model without database fields, used when fetching
         *     conversation history from the agent checkpoint.
         */
        CheckpointMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /**
         * ExecutionLog
         * @description Execution log model with all fields.
         */
        ExecutionLog: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /** Taskid */
            taskId?: string | null;
            eventType: components["schemas"]["ExecutionLogEventType"];
            /** Eventdata */
            eventData: {
                [key: string]: unknown;
            };
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * ExecutionLogEventType
         * @description Execution log event type enum.
         * @enum {string}
         */
        ExecutionLogEventType: "task_selected" | "tool_call" | "tool_result" | "content" | "reflection" | "task_completed" | "artifact_analysis_start" | "artifact_analysis_complete" | "artifact_created" | "error" | "done";
        /**
         * ExecutionLogsResponse
         * @description Response model for execution logs endpoint.
         */
        ExecutionLogsResponse: {
            /** Logs */
            logs: components["schemas"]["ExecutionLog"][];
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Session
         * @description Session model with all fields.
         */
        Session: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Title */
            title: string;
            /** @default planning */
            status: components["schemas"]["SessionStatus"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * SessionDetail
         * @description Session with related data for detail view.
         */
        SessionDetail: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Title */
            title: string;
            /** @default planning */
            status: components["schemas"]["SessionStatus"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Tasks */
            tasks?: components["schemas"]["Task"][];
            /** Messages */
            messages?: components["schemas"]["CheckpointMessage"][];
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactSummary"][];
        };
        /**
         * SessionStatus
         * @description Session status enum.
         * @enum {string}
         */
        SessionStatus: "planning" | "executing" | "completed";
        /**
         * Task
         * @description Task model with all fields.
         */
        Task: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default pending */
            status: components["schemas"]["TaskStatus"];
            /** Order */
            order: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sessionid
             * Format: uuid
             */
            sessionId: string;
            /** Result */
            result?: string | null;
            /** Reflection */
            reflection?: string | null;
        };
        /**
         * TaskStatus
         * @description Task status enum.
         * @enum {string}
         */
        TaskStatus: "pending" | "in_progress" | "done" | "failed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["SessionStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_sessions__session_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_tasks_sessions__session_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_session_sessions__session_id__summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_logs_sessions__session_id__execution_logs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionLogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_sessions__session_id__artifacts_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["ArtifactType"] | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["ArtifactSummary"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_sessions__session_id__artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_artifact_sessions__session_id__artifacts__artifact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_sessions__session_id__artifacts__artifact_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
